version: "3.5"

services:
  db:
    image: mariadb:10.7
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./mount/db:/var/lib/mysql"
    environment:
      - "TZ=UTC"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_password"
    restart: always
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user

  app:
    image: oaooa/pichome
    ports:
      - 8095:80
    links:
      - db
    volumes:
      - "./mount/site:/var/www/html"
    environment:
      - "MYSQL_SERVER=db"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_password"
    restart: always
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user



secrets:
  mysql_db:
    file: "./mysql_db.txt"
  mysql_password:
    file: "./mysql_password.txt"
  mysql_user:
    file: "./mysql_user.txt"
